
<html dir="rtl" lang="ar">

<head>
  <meta charset="UTF-8">
  <meta charset="UTF-8">
.</head>

<body>gnjnj

  <p>نوف.</p>
  <h1> منصةصحتي </h1>
  <p> منصة وزارةالصحة </br> التي ساعدني فيالتعليم </p>

  <h2>{ اقسان منصةصحتي</h2>
  <ol>
    <li> الواجبات </li>
    <li>اختبارات</li>
    <label> الجنه </label><br>
    
    
    <li>الجدول المدرسي</li>
  </ol>
  <a href="  http://slenquirysehasa.ddns.net/Home/Login  "> اضغط هون </a>
<label for="">    منصة   </label>
    
